components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
 
        fs-task-processor:
            worker_threads: 1
 
    default_task_processor: main-task-processor
 
    components:
        server:
            listener:
                port: 8015
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard
 
        handler-message:
            path: /api/v1/message
            method: GET,POST
            task_processor: main-task-processor
